### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [jpweist/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
This object named `Classic Breakfast` would be an instance of a class called `Menu Item`, but the class `Breakfast Menu` would have instances such as `Mcdonald's Breakfast Menu` or `Chick-fil-a Breakfast Menu`. Does that example make sense? I'm happy to explain further just let me know Remember that the class is the blueprint to make many different instances of itself that share the same types of attributes, but probably have different values stored in those attributes. 
- [] I listed the values for each attribute of this object.
For a boolean value we use true or false instead of yes or no. For a string we'd like to see the value surrounded in quotes. For an array we use `[ ]` brackets and commas to separate each value in the array. 
- [x] I listed the results of each method for this object. 
In general we want these methods to actually change the attributes you've listed, not keep them the same.
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
These are mostly solid, other than `add staff member`. Creating a new staff member implies instantiating a new object. Also, there's no array or hash/object to store this staff member in which we would usually find in the attributes of the class. If you had an attribute called staff_members that was an array or hash/object then this would make more sense. But your attributes are setup in a way that makes more sense if you called your class `Employee` or `Staff Member`, because `Staff` implies that there are multiple members. Let me know if you have questions about this! 
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
You did well on this one other than the `add staff member` method, because it has no corresponding attribute.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
Committed with object file.

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
This would make more sense if you changed the name of your class to `Employee`. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
Committed with class file.

Hey Jim, we'd like you to go ahead and make the changes that I've outline in the feedback above. Each time you make a change to a file, make sure to commit that change separately and with a properly formatted commit message (present tense, capital letter and verb to start). I think you're close to having a passing assessment, but some of the methods/attributes/classes need some name changing so that they all sync up. Let me know if you have questions about the feedback. We'd like to see you have these updates to us by EOD Monday. Thanks Jim!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by jpweist** [comment]
made change requested to the file having trouble pushing it back.

**Comment by timomitchel** [comment]
Hey @jpweist ! Thanks for implementing the changes. This is looking better, but there are still a few things that need to be addressed. For example, take a look at your method names, and make sure they are exactly the same in both the class and corresponding object example files. Clean up any typos you find. And, make sure that all of the methods that you chose are present tense verbs. `Work` would be a good method name that changes the attribute `working` to true. Does that all make sense? Also, I think the class naming is still a bit unclear. With the 5 attributes you added, class_1 sounds like it is made up partly of  a `Restaurant` class and partly of a `Menu Item` class. A `Breakfast Menu` class would have attributes like `material` (string) `items` (array) `kid_section?` (boolean), but what you are describing in the first few attributes is a **single** item that would occur on a breakfast menu. Please pick one of the classes I have described above, and make sure all attributes/methods only belong with the class you've chose. Don't hesitate to ask questions along the way. We will keep the EOD Monday deadline for these changes. Thanks Jim!

**Comment by jpweist** [comment]
Hi, i updated the class files for the files. I removed the extra attributes that implied that it was for the restaurant and checked the misspellings. Before I think i was trying to add everything to it. How does it look?
